version: '2.0'
 
# Define the services/ containers to be run
services:
 angular: # name of the first service
  build: angular-app
  ports:
  - "4200:4200"
 
 express: # name of the second service
  build: express-server
  ports:
  - "3000:3000"
 
 database: # name of the third service
  image: mongo
  ports:
  - "27017:27017"
